[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.152.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_VERSION = "0.152.2"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
  

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/wp/category/home-assistant/"
  to = "/tags/home-assistant/"
  status = 301

[[redirects]]
  from = "/wp/tag/problem-solving/"
  to = "/tags/home-assistant/"
  status = 301

[[redirects]]
  from = "/wp/wp/tag/w1209wk/"
  to = "/tags/"
  status = 301

[[redirects]]
  from = "/wp/tag/termostato/"
  to = "/tags/"
  status = 301

[[redirects]]
  from = "/wp/tag/home-assistant/"
  to = "/tags/home-assistant/"
  status = 301

[[redirects]]
  from = "/wp/7-migliori-stampanti-3d-in-resina-per-principianti-nel-2021-alta-qualita/"
  to = "/categories/stampa-3d/"
  status = 301

[[redirects]]
  from = "/wp/installare-samba-su-home-assistant/"
  to = "/tags/home-assistant/"
  status = 301

[[redirects]]
  from = "/wp/non-estrude-a-inizio-stampa/"
  to = "/posts/stampante-3d-fdm-non-estrude-inizio-stampa/"
  status = 301